### PR TITLE
Design updates

### LINKED ISSUE #98: Petty Styling improvements
## Description
Look at these ugly cards holding everything. so much weird wasted space and the pollution guidelines section looks so weird cause it's not the height of everything else (as it's set for a pixel value). Here's my suggested improvements
### General Styling Improvements
Stuff needs to get moved to percentages, no more pixels on that stylesheets apart from borders! 
### Specific and very nitpicky improvements
- [ ] 1. Make sure that the pollution guidelines isn't just an arbitrary pixel value
- [x] 2. Move around some of the cards so it makes more logical sense (What would the user be searching for first?)
- [x] 3. The margin-left and margin-right of the cards are a little off, think they can be made slightly smaller (and percentaged!)
- [x] 4. The borders look too bootstrappy, maybe a slight border shadow/inset could help it (or just change the colours and make it smaller)
- [x] 5. The colours of the carousel aren't right, and should be based on another colour on the website (maybe the light blue of the sidebar?) Also the left and right arrows shouldn't really need a background.
image

- [x] 1. The top logo needs to be slightly higher, and the bottom logo needs to be slightly lower
- [x] 2. Each section in the sidebar should have a logo, especially now we're adding a few more sections.)

image

## The actual vs expected behaviour
It needs to look nicer

## Additional Information
I'm slightly insane

### PR DESCRIPTION
**Pull request by M-Davies**
* General makes everything smoother and less bootstrappy
* Adds icons to sidebar
* Re-arranges cards
* See branch for more details

Closes: #98

### CODE REVIEW

**Comment by M-Davies** [comment]
Draft for now while I wait for more ideas to pop into my head

**Review by Megan-Wright — COMMENTED** [review]
Looking a lot better in general definitely - just a few thoughts I've had... 
- I feel like the icons should be on the left of the menu items (just so they line up nicely with each other)?
- Not sure why the weather title has a grey background and the rest don't?
- That little bit of white space underneath the weather panel is still annoying... not sure if there's a lot we can do about that though without changing the design of the whole page :/
- We need to decide on either colons after the card titles or not (at the moment we have two titles with a colon and two without) Personally idc either way I just like consistency 😂 

All open for discussion obviously :)

**Comment by dambem** [comment]
No colons after title cards (executive decision i hate colons)

**Comment by AlvaroRausell** [comment]
Colons are very important organs, please do not ever undermine their job ever again.
Thanks

**Comment by dambem** [comment]
https://material-theme-builder.glitch.me/

**Comment by M-Davies** [comment]
> That little bit of white space underneath the weather panel is still annoying... not sure if there's a lot we can do about that though without changing the design of the whole page :/

You're right on that. I tried to reorganise everything but it proved way too clunky in the end. Without some serious work on the layout, that whitespace will have to stay (unless anyone wants to look into dealing with it, feel free)

Anyway check out the branch now and let me know what you think

**Comment by Megan-Wright** [comment]
@M-Davies looking better :) nice lack of colons and a grey header, however not sure whats going on here....
Screenshot 2020-07-27 at 12 59 34

**Comment by M-Davies** [comment]
Huh. That looked fine on my end. What's your zoom/font factor on your web browser out of curiosity?

**Comment by M-Davies** [comment]
@Megan-Wright Fixed, can I get a re-review?

**Comment by dambem** [comment]
Apologies for this, i really wanted to get in some of the box-shadow improvements, and remove some borders to just sort of reduce some noise. One very petty thing and it's gonna seem completely weird, 

the logos should be a black border, with each icon having a different colour from the urbanflows logo at the bottom. There's just something about a fully black icon that's not sitting fully right with me, and i think that's just my styling issues coming into play

**Comment by Megan-Wright** [comment]
> @Megan-Wright Fixed, can I get a re-review?

Yep I'm happy with it now when Damian's comment has been addressed :)

**Comment by dambem** [comment]
image
Also, the colours here might work better as the deep purple of the logo, then the cyan dot. They're so similar and so close together

**Comment by M-Davies** [comment]
> > @Megan-Wright Fixed, can I get a re-review?
> 
> Yep I'm happy with it now when Damian's comment has been addressed :)

Done

**Comment by dambem** [comment]
Perfect, accepted

**Review by dambem — APPROVED** [review]

**Comment by M-Davies** [comment]
Ah I didn't see [this comment](https://github.com/dambem/ClimateMonitorV2/pull/104#issuecomment-665017355). @dambem Can you implement that for me since you already have the css ready? :)

**Pull request merged**
