### PR TITLE
Changing the colouring of the gauge to reflect pre-existing styling on page

### PR DESCRIPTION
**Pull request by dambem**
Just a small fix of making the colouring of the gauge be a bit more like the colours that already exists

### CODE REVIEW

**Review by M-Davies — CHANGES_REQUESTED** [review]
Might need to rebase as I just merged your other PR which has one of your commits on master already (sorry!)

**Comment by AlvaroRausell** [comment]
@dambem Those colours are this way to match the AQI standards. I don't think they should be changed as they are the most "official" way of representing the data.

**Comment by dambem** [comment]
Compromise, as all of them are arguably different shades of the same colour apart from the blue, what i just change the current blue to a better green?

**Comment by dambem** [comment]
will rebase cheers @M-Davies

**Comment by AlvaroRausell** [comment]
@dambem sounds good 👍

**Comment by dambem** [comment]
lovely little green instead

**Comment by dambem** [comment]
@AlvaroRausell gimme that approval

**Comment by AlvaroRausell** [comment]
@M-Davies Gotta approve those requested changes before I give the green light

**Comment by dambem** [comment]
I see what you did there

**Review by M-Davies — APPROVED** [review]
Yeah go ahead with this one chief

**Pull request merged**
