### PR TITLE
Add mortality particle simulation

### LINKED ISSUE #116: Particles
## Description
Let's get some interesting things using WebGL particles going

### PR DESCRIPTION
**Pull request by AlvaroRausell**

### CODE REVIEW

**Review by Megan-Wright — CHANGES_REQUESTED** [review]
Looks amazing - love it :) One minor criticism in that the GUI placement seems slightly odd and it's not entirely obvious that it's connected to the simulation.... love that its filling the what space just maybe make it bigger or closer to the display? 
Screenshot 2020-08-10 at 23 14 34

Also, capitalise the title please (sorry my slight OCD getting the better of me)

**Comment by dambem** [comment]
Looks amazing! Just a couple of comments on making the presentation, all of which are quite small points! 

1. Make sure to have a legend of black particle =polluted, blue particle = unpolluted

2. Can we have a parameter slider for the pollution level that just starts out as the current value instead? (One for PM2 and one for PM10) Might be quite interesting to just see how badly it really is effecting health at higher levels without needing to actually be in that environment 

3. Just a small dramatic preface, something along the lines of "each dot represents a persons average lifespan, left click to see a polluted lifespan, and right-click to see a life adhering to pollution standards"

4. Non vulnerable particles as the same green in the air quality measure, vulnerable as the same dark purple? I know it's getting a bit picky at that point but i think the colours would be slightly clearer and easier to differentiate

**Comment by dambem** [comment]
Ah ignore my last message, shouldn't be reviewing stuff at half to midnight. You can in fact change the pollution value, which is great! The one comment is can you instead click to send both the vulnerable and non-vulnerable particles at once? I think it might be easier to see the difference in that way

Also, can you just slightly increase the lifespan? just to the living particles hold for a little bit longer

**Comment by dambem** [comment]
Accepted, can you just fix the conflicts

**Review by Megan-Wright — APPROVED** [review]

**Pull request merged**
