### PR TITLE
Sidebar setup and carosuel enhancements

### LINKED ISSUE #57: Sideways Menu
## Description
This is more of a dashboard. A side menu would be quite a lot better looking for users, and i think just make everything look a little bit nicer. 

## Steps to reproduce
n/a 

## The actual vs expected behaviour
actual behaviour - it's at the top 
expected - we want it to be at the side

### PR DESCRIPTION
**Pull request by M-Davies**
## Description of this PR
* Changed the navbar into a sidebar that highlights the current page
* Added link to github
* Removed ugly captions from carosuel, made images themselves hyperlinks
* Pug files now use the same tab/space size

## Relevant issue
Closes: #57 

## Checklist
- [x] Tests all pass

### CODE REVIEW

**Comment by M-Davies** [comment]
Sidebar now looks like this:
Screenshot 2020-07-15 at 12 56 34
Checkout the branch if you want to have a nose around (@dambem You might want to do that to verify that the `PM10 and PM2.5 Values Of Sensor` popup isn't in a weird place on the page. It looked fine on my laptop but better safe than sorry)

**Review by dambem — APPROVED** [review]
This seems to work properly!

**Comment by dambem** [comment]
Ahh, quick conflict with megans latest request, should be a small change though!

**Comment by M-Davies** [comment]
> Ahh, quick conflict with megans latest request, should be a small change though!

Done

**Pull request merged**
