### PR TITLE
NEW ADMIN: alvaro.rausellg@gmail.com

### PR DESCRIPTION
**Pull request by AlvaroRausell**
Take 2 :)

### CODE REVIEW

**Review by M-Davies — APPROVED** [review]
Ok so I think I managed to get this working. @AlvaroRausell Can you give this a try using the instructions in the README?
```
========== blackbox administrators are:
alvaro.rausellg@gmail.com
D032F5A258A25494
meganw33@hotmail.com
morgandavies2020@gmail.com
```

**Comment by M-Davies** [comment]
Poke @AlvaroRausell

**Comment by AlvaroRausell** [comment]
:(
image

**Comment by M-Davies** [comment]
@AlvaroRausell Pull in the changes and try now?

**Comment by AlvaroRausell** [comment]
Nope, same error

**Comment by M-Davies** [comment]
Closing since blackbox is being removed

**Pull request closed without merging**
