### PR TITLE
Caroseled python graphs

### LINKED ISSUE #64: Pre-Existing Python Graphs on Website
## Description
in public/files we have a couple of nice looking long term python visualisations! Could be good to get them displayed somewhere on the page.

### PR DESCRIPTION
**Pull request by M-Davies**
## Relevant issue
Closes #64 

## Description of this PR
- Adds in a carousel that displays the python graphs now in their new home in the `/images` folder
- Uses the github api to pull the images publicly because creating a private route is too much of a pain in the ***
- Also cleans up a bunch more files

### CODE REVIEW

**Comment by M-Davies** [comment]
@dambem @Megan-Wright Please see the last bullet point for why this is a draft 😜

**Comment by dambem** [comment]
I'll take a look at fixing some of it later today

(also add package-lock.json to that gitignore)

**Comment by M-Davies** [comment]
Now working. I am an idiot for using `i` in a for loop which didn't use `i` declared 🤦 . Ready for review

**Comment by dambem** [comment]
Accepted! Everybody has those days, everybody makes mistakes - hannah montanah

**Review by dambem — APPROVED** [review]

**Pull request merged**
