### PR TITLE
Initial python script checker

### LINKED ISSUE #113: Python Script Checker
## Description
Add a Github check step on our pull requests that checks that our python scripts run ok. Since we have a lot of changes coming in, we should have this to ensure our scripts are not broken by future commits.

### PR DESCRIPTION
**Pull request by M-Davies**
Runs a github check that downloads a 3.x version of python, installs dependancies and runs flake8 to lint the files. I also added an npm script (`pylint`) so you can run the flake8 command locally from anywhere in the `ClimateMonitorV2/ClimateMonitorV2` directory. All python files have been updated to account for this change so only new contributions will break flake8.

Closes: #113

### CODE REVIEW

**Comment by dambem** [comment]
Great! Although maybe hold off on it compiling the filegetter script, mostly as in it's current state it might download a very large amount of files onto the system!

**Comment by M-Davies** [comment]
> Great! Although maybe hold off on it compiling the filegetter script, mostly as in it's current state it might download a very large amount of files onto the system!

I should be able to add an `afterCompletion` script that cleans up files

**Comment by dambem** [comment]
Looks good, cheers for cleaning up some of the code! @Milad-Laly just want to check this isn't conflicting with anything you're doing before i pop it through

**Comment by M-Davies** [comment]
Please don't merge yet. I kinda forgot to verify if the python files still run 😬

**Comment by M-Davies** [comment]
graphmaker.py & full_time_display.py can't run as the required files for today don't exist (it was my understanding that they are broken anyway). All others run fine but I don't know if they work as there's no documentation on how they work or what order to run them in (opened https://github.com/dambem/ClimateMonitorV2/issues/128 for that)

**Review by dambem — APPROVED** [review]

**Pull request merged**
